### ISSUE TITLE
Single letter "c" search causes error - trie.js:6 Uncaught TypeError: function is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by chrisj74** [LyraSearch/lyra#137]
**Describe the bug**
Searching for letter `c` causes error:
```
trie.js:6 Uncaught TypeError: function is not iterable (cannot read property Symbol(Symbol.iterator))
    at new Set (<anonymous>)
    at findAllWords (trie.js:6:44)
    at findAllWords (trie.js:6:176)
    at findAllWords (trie.js:6:176)
    at findAllWords (trie.js:6:176)
    at findAllWords (trie.js:6:176)
    at findAllWords (trie.js:6:176)
    at findAllWords (trie.js:6:176)
    at findAllWords (trie.js:6:176)
    at findAllWords (trie.js:6:176)
findAllWords @ trie.js:6
findAllWords @ trie.js:6
findAllWords @ trie.js:6
findAllWords @ trie.js:6
findAllWords @ trie.js:6
findAllWords @ trie.js:6
findAllWords @ trie.js:6
findAllWords @ trie.js:6
findAllWords @ trie.js:6
findAllWords @ trie.js:6
findAllWords @ trie.js:6
find @ trie.js:6
getDocumentIDsFromSearch @ lyra.js:4
search @ lyra.js:74
searchHistory @ search.js:79
handleChange @ global-search.js:136
```
I have hacked about this by preventing single string searches and deferred searching until at least 3 chars, but have discovered that `.` acts as a word separator, so searching `github.c` also causes the error. My search needs to index domain names, so this is an issue.

Other letters work fine.

**To Reproduce**
This is the basic code I am using:
```
async createSearchIndex() {
		this.historyDB = create({
			schema: {
				title: 'string',
				heading: 'string',
				description: 'string',
				url: 'string',
				historyId: 'string',
			},
		});
	}

	async insertSearchData(data) {
		if (!this.historyDB) {
			this.createSearchIndex();
		}
		await insertBatch(this.historyDB, data, { batchSize: 500 });
		generateScores(this.historyDB);
	}

	searchHistory(searchTerm) {
		const searchResult = search(this.historyDB, {
			term: searchTerm,
			properties: ['title', 'url', 'description'],
			tolerance: 1,
		});
		return searchResult;
	}
```
I'm loading an initial batch of ~1000 docs and then updating in smaller batches 1-2.

Everything works fine unless I search for a single character `c`

**Expected behavior**
No error

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - Browser Chrome
 - Version 105

**Smartphone (please complete the following information):**
N/A

**Additional context**
This is running in an emberjs app. It is wrapped in a service with the data being passed in from a different service.

Thanks for creating - any help much appreciated

**Comment by micheleriva** [comment]
Hi @chrisj74 ,
Thanks for opening this. It looks quite strange, we should catch this kind of issue with our CI right before the release.

Let me look into that - any suggestion on how to fix this/PR would be highly appreciated given that you already identified a possible point of failure 🙂

**Comment by micheleriva** [comment]
Hi @chrisj74 , would you be able to create a reproducible repo either via codesandbox or on github? I am not able to replicate the problem

**Comment by lucaong** [comment]
@chrisj74 @micheleriva this is because the character `c`  matches the term `constructor` in the index. You can probably reproduce this issue by adding a document containing the word `constructor` and search for it.

The issue is that the property `constructor` in any JS object returns a function, namely the constructor function for the object:

```js
let x = {}
x['constructor']
// => function Object() {
//        [native code]
//    }
```

This is why [MiniSearch](https://github.com/lucaong/minisearch) never blindly accesses arbitrary object properties, and instead [only considers own properties](https://github.com/lucaong/minisearch/blob/2e2b3b791858abf665c842800069728c8e3666c1/src/MiniSearch.ts#L1204) whenever it accesses plain objects.

**Comment by micheleriva** [comment]
Thank you so much @lucaong, you are totally right. I’m going to open a PR for this on Thursday and make a release to fix this immediately.

**Comment by chrisj74** [comment]
@micheleriva  Thanks for speedy turnaround. 

@lucaong thanks for taking the time to flesh out the issue.

**Comment by lucaong** [comment]
Welcome :)
